"""add_featured_image_url_to_posts

Revision ID: ab7be35a23ee
Revises: 2936770221dc
Create Date: 2025-05-17 23:59:02.666643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Quan trọng: Đảm bảo bạn đã import sqlmodel nếu dùng các kiểu dữ liệu của nó,
                # nhưng ở đây chúng ta chỉ dùng các kiểu cơ bản của SQLAlchemy (sa) cho cột.


# revision identifiers, used by Alembic.
revision: str = 'ab7be35a23ee'
down_revision: Union[str, None] = '2936770221dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Thêm cột featured_image_url vào bảng 'post'
    # Kiểu dữ liệu là String, và cho phép giá trị NULL (nullable=True)
    op.add_column('post', sa.Column('featured_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Xóa cột featured_image_url khỏi bảng 'post' khi rollback
    op.drop_column('post', 'featured_image_url')
    # ### end Alembic commands ###
